# https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr1.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr2.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr3.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr4.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr5.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr6.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr7.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr8.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr9.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr10.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr11.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr12.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr13.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr14.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr15.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr16.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr17.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr18.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr19.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr20.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr21.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chr22.EUR.tsv.gz
wget https://data.broadinstitute.org/srlab/BEAGLE/1kG-beagle-release3/pairwise_ld/r2_ge_0.8/chrX.EUR.tsv.gz