## First question: How number of GFs affects run time
#all:	1_vs_xENCODE_precalc_annot
#all:	1_vs_xENCODE_noprecalc_annot
# Get time of run
# for file in `find . -type f -name gr_log.txt`; do echo -ne `dirname $file`"\t"; head -1 $file | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -4 $file | head -1 | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -1 $file | cut -d ' ' -f1-2; done > ../1_vs_xENCODE_precalc_annot.txt
## Second question: How the number of SNP sets affects run time
all:	x_vs_ENCODE_precalc_annot 
#all:	x_vs_ENCODE_noprecalc_annot
# Get time of run
# for file in `find . -type f -name gr_log.txt`; do echo -ne `dirname $file`"\t"; head -1 $file | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -4 $file | head -1 | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -1 $file | cut -d ' ' -f1-2; done > ../x_vs_ENCODE_precalc_annot.txt
## Third question: How the size of SNP set affects run time
#all:	1x_vs_ENCODE_precalc_annot
#all:	1x_vs_ENCODE_noprecalc_annot
# Get time of run
# for file in `find . -type f -name gr_log.txt`; do echo -ne `dirname $file`"\t"; head -1 $file | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -4 $file | head -1 | cut -d ' ' -f1-2 | tr -d "\n"; echo -ne "\t"; tail -1 $file | cut -d ' ' -f1-2; done > ../1x_vs_ENCODE_precalc_annot.txt

SHELL=/bin/bash
# Full path to the background file, which also serves as source of randomly selected SNPs
SNP=/home/mdozmorov/db_5.00_07-22-2015/custom_data/backgrounds/hg19/1snp142Common.bed.gz
# Size of a SNP set
SIZE =1000
# Path to the ENCODE dataset
GRSNP_DB = /home/mdozmorov/db_5.00_07-22-2015/grsnp_db/hg19/ENCODE
# Path to the full database
DB=/home/mdozmorov/db_5.00_07-22-2015/

## First question: How number of GFs affects run time
# 1 SNP set vs variable number of genomic features, precalculated, annotation
1_vs_xENCODE_precalc_annot:
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi; \
	cd $@; \
	echo "Creating SNP set with" $(SIZE) "SNPs..."; \
	zcat $(SNP) | shuf | head -n $(SIZE) >  bed/rndSNP_$(SIZE).bed; \
	find `pwd`/bed -type f -name rndSNP_$(SIZE).bed > fois.txt; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((100*i)); \
		echo "Running 1 set of" $(SIZE) "SNPS vs." $$n "genome annotation features..."; \
		cat gfs.hg19.ENCODE.txt | shuf | head -n $$n > gfs.hg19.ENCODE_$$n.txt; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE_$$n.txt $(SNP) -d $(DB) -r "1_vs_"$$n"ENCODE_precalc_annot" --run_annotation; \
	done; \
	cd ..

# 1 SNP set vs variable number of genomic features, not precalculated, annotation
1_vs_xENCODE_noprecalc_annot:
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi; \
	cd $@; \
	echo "Creating SNP set with" $(SIZE) "SNPs..."; \
	zcat $(SNP) | shuf | head -n $(SIZE) >  bed/rndSNP_$(SIZE).bed; \
	find `pwd`/bed -type f -name rndSNP_$(SIZE).bed > fois.txt; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((100*i)); \
		echo "Running 1 set of" $(SIZE) "SNPS vs." $$n "genome annotation features..."; \
		cat gfs.hg19.ENCODE.txt | shuf | head -n $$n > gfs.hg19.ENCODE_$$n.txt; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE_$$n.txt $(SNP) -r "1_vs_"$$n"ENCODE_noprecalc_annot" --run_annotation; \
	done; \
	cd ..

## Second question: How the number of SNP sets affects run time
# Multiple SNP sets vs all ENCODE data, precalculated, annotation
x_vs_ENCODE_precalc_annot:
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi; \
	cd $@; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" | shuf | head -n 1000 > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((10*i)); \
		echo "Creating SNP set with" $(SIZE) "SNPs..."; \
		zcat $(SNP) | shuf | head -n $(SIZE) >  bed/rndSNP_$(SIZE).bed; \
		number=1 ; while [[ $$number -le $$n ]] ; do \
			echo $$number ; \
			cp bed/rndSNP_$(SIZE).bed bed/rndSNP_$(SIZE)_$$number.bed; \
			((number = number + 1)) ; \
		done; \
		rm bed/rndSNP_$(SIZE).bed; \
		echo "Running " $$n " sets of SNPS vs. 1000 genome annotation features..."; \
		find `pwd`/bed -type f -name "*.bed" > fois.txt; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE.txt $(SNP) -d $(DB) -r $$n"_vs_ENCODE_precalc_annot" --run_annotation; \
		rm fois.txt; \
	done; \
	cd ..

# Multiple SNP sets vs all ENCODE data, not precalculated, annotation
x_vs_ENCODE_noprecalc_annot:
	SHELL=/bin/bash;\
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi; \
	cd $@; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" | shuf | head -n 1000 > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((10*i)); \
		echo "Creating SNP set with" $(SIZE) "SNPs..."; \
		zcat $(SNP) | shuf | head -n $(SIZE) >  bed/rndSNP_$(SIZE).bed; \
		number=1 ; while [[ $$number -le $$n ]] ; do \
			echo $$number ; \
			cp bed/rndSNP_$(SIZE).bed bed/rndSNP_$(SIZE)_$$number.bed; \
			((number = number + 1)) ; \
		done; \
		rm bed/rndSNP_$(SIZE).bed; \
		echo "Running " $$n " sets of SNPS vs. 1000 genome annotation features..."; \
		find `pwd`/bed -type f -name "*.bed" > fois.txt; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE.txt $(SNP) -r $$n"_vs_ENCODE_noprecalc_annot" --run_annotation; \
		rm fois.txt; \
	done; \
	cd ..

## Third question: How the size of SNP set affects run time
# 1 SNP set of variable size vs all genomic features, precalculated, annotation
1x_vs_ENCODE_precalc_annot:
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi;\
	cd $@; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" | shuf | head -n 1000 > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((100*i)); \
		echo "Creating SNP set with" $$n "SNPs..."; \
		zcat $(SNP) | shuf | head -n $$n >  bed/rndSNP_$$n.bed; \
		find `pwd`/bed -type f -name "*.bed" > fois.txt; \
		echo "Running 1 set of" $$n "SNPS vs.1000 genome annotation features..."; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE.txt $(SNP) -d $(DB) -r "1_"$$n"_vs_ENCODE_precalc_annot" --run_annotation; \
		rm bed/rndSNP_$$n.bed; \
	done; \
	cd ..

# 1 SNP set of variable size vs all genomic features, not precalculated, annotation
1x_vs_ENCODE_noprecalc_annot:
	if [ ! -d $@ ]; then \
		mkdir $@; \
		mkdir $@/bed; \
	fi; \
	cd $@; \
	find $(GRSNP_DB) -type f -name "*.bed.gz" | shuf | head -n 1000 > gfs.hg19.ENCODE.txt; \
	for i in {1..10}; do \
		n=$$((100*i)); \
		echo "Creating SNP set with" $$n "SNPs..."; \
		zcat $(SNP) | shuf | head -n $$n >  bed/rndSNP_$$n.bed; \
		find `pwd`/bed -type f -name "*.bed" > fois.txt; \
		echo "Running 1 set of" $$n "SNPS vs.1000 genome annotation features..."; \
		python -m grsnp.hypergeom4 fois.txt gfs.hg19.ENCODE.txt $(SNP) -g hg19 -r "1_"$$n"_vs_ENCODE_noprecalc_annot" --run_annotation; \
		rm bed/rndSNP_$$n.bed; \
	done; \
	cd ..
