# Example of automating GenomeRunner enrichment analyses via command line
# Analysis of selected SNPs from a region against categories of genomic features.
# Input: $(INP).bed file with coordinates of the SELECTED SNPs
#        $(INP)_region.bed file with coordinates of the region
# flanking selected SNPs. This file is used to extract coordinates
# of ALL SNPs from the region, to be used as a background $(INP)_bkg.bed
# Contact Mikhail dot Dozmorov at gmail dot com

# Prefix for .bed and _region.bed file names
INP = 13qq14_11
# Path to the genomic background from which ALL region-specific SNPs
# will be extracted
BKG = /home/mikhail/test_db/custom_data/backgrounds/hg19/2snp138+.bed.gz
# GenomeRunner folder containing analysis-specific lists (categories) of
# genomic features to be used tor the analysis
GR = /home/mikhail/work/genomerunner/
# Roots of file names containing lists (categories) of genomic features
# File name format: gfs.hg19.$(AN).txt
# See Help section on http://www.genomerunner.org for the interpretation
AN1 = BroadHistone
AN2 = BroadHmm
AN3 = HaibTfbs
AN4 = HaibMethyl450
AN5 = HaibMethylRrbs
AN6 = OpenChromSynth
AN7 = UwDgf
AN8 = UwDnase
AN9 = UwHistone
AN10 = UwRepliSeq
AN11 = UwTfbs

# Not used
# AffyRnaChipFiltTransfrags
# CshlLongRnaSeq
# CshlShortRnaSeq
# GisChiaPet
# GisRnaPet
# HaibGenotype
# RikenCage
# Special
# SunyAlbanyGeneSt
# SunyAlbanyTiling
# SunyRipSeq
# SunySwitchgear
# UmassDekker5C

# Variable/function to execute $@ analysis.
# Note that .$@ is passed to reconstruct gfs file names
# Results are generated in the analysis-specific folders
define hypergeom4
python -m grsnp.hypergeom4 --output_dir GR$@ foi.txt $(GR)enc.hg19$@.txt $(INP)_bkg.bed
endef

all:			.$(AN1) .$(AN2) .$(AN3) .$(AN4) .$(AN5) .$(AN6) .$(AN7) .$(AN8) .$(AN9) .$(AN10) .$(AN11)
# Create a background of all SNPs from the region
$(INP)_bkg.bed:
				intersectBed -wa -u -a $(BKG) -b $(INP)_region.bed > $(INP)_bkg.bed
# Create a list of file name(s) to be analyzed for enrichment
foi.txt:
				ls $(INP).bed > foi.txt
# Lists (categories) of genomic features to be used for the enrichment analysis
# All analyses depend on the presence of the background and the foi.txt file
# A .$(AN) file is created upon completion of the analysis
.$(AN1):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN1)
.$(AN2):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN2)
.$(AN3):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN3)
.$(AN4):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN4)
.$(AN5):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN5)
.$(AN6):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN6)
.$(AN7):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN7)
.$(AN8):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN8)
.$(AN9):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN9)
.$(AN10):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN10)
.$(AN11):		$(INP)_bkg.bed foi.txt
				$(hypergeom4)
				touch .$(AN11)