all:	hg19 mm9

# Create CpG BED files, from http://rafalab.jhsph.edu/CGI/

model-based-cpg-islands-hg19.txt:
	wget http://rafalab.jhsph.edu/CGI/model-based-cpg-islands-hg19.txt

hg19:	model-based-cpg-islands-hg19.txt
	sed '1d' $< | grep "\bchr[0-9XYM][^_]\b" | awk 'BEGIN {OFS="\t"} { if ( $$3 <= $$2) { print $$1, $$2, $$2+1 } else { print $$1, $$2, $$3 } }' | sort -k1,1 -k2,2n -k3,3n | uniq > CpG-$@.bed;
	bgzip CpG-$@.bed;
	tabix CpG-$@.bed.gz


model-based-cpg-islands-mm9.txt:
	wget http://rafalab.jhsph.edu/CGI/model-based-cpg-islands-mm9.txt

mm9:	model-based-cpg-islands-mm9.txt
	sed '1d' $< | grep "\bchr[0-9XYM][^_]\b" | awk 'BEGIN {OFS="\t"} { if ( $$3 <= $$2) { print $$1, $$2, $$2+1 } else { print $$1, $$2, $$3 } }' | sort -k1,1 -k2,2n -k3,3n | uniq > CpG-$@.bed;
	bgzip CpG-$@.bed;
	tabix CpG-$@.bed.gz