## Creates a merged background file from the 'ENCODE' and 'genes' annotations
##
## Prerequisites:
##     The GenomeRunner database should be created
##     Create 'Cistrome' folder, 'hg19' and 'mm9' subfolders, and 'Cistrome', 'Epigenome' and 'Motif' subsubfolders
##
## Note: Scripts are still not automatic, due to non-standard .zip files

DB = /home/genomerunner/db_3.00_12-01-2014
ORG = hg19

#all:	$(ORG)_background_all.bed $(ORG)_background_HTD.bed
all:	hg19_background-rmsk.bed.gz

# Background encompasses genes and ALL ENCODE data. Nearly the same as all chromosomes
$(ORG)_background_all.bed:
	echo "Processing genes" ; \
	for file in `find $(DB)/grsnp_db/$(ORG)/genes/ -type f -name "*.bed.gz"`; do \
		zcat $$file | grep "\bchr[0-9XYM][^_]\b" >> genes.bed; \
	done; \
	echo "Sorting and merging genes"; \
	cut -f1-3 genes.bed | sort -k1,1 -k2,2n > genes_sorted.bed && \
	mergeBed -i genes_sorted.bed > genes.bed && \
	rm genes_sorted.bed; \
	echo "Processing ENCODE"; \
	for file in `find $(DB)/grsnp_db/$(ORG)/ENCODE/ -type f -name "*.bed.gz"`; do \
		zcat $$file | grep "\bchr[0-9XYM][^_]\b" >> encode.bed; \
	done; \
	echo "Sorting and merging ENCODE"; \
	cat encode.bed | sort -k1,1 -k2,2n | gzip > encode_sorted.bed.gz && \
	rm encode.bed; \
	mergeBed -i encode_sorted.bed.gz |gzip > encode.bed.gz && \
	gunzip encode.bed.gz && \
	cat genes.bed encode.bed | sort -k1,1 -k2,2n | uniq > genes_encode.bed && \
	mergeBed -i genes_encode.bed > $@; \
	rm genes_encode.bed

# Background encompasses genes and Histone/Tfbs/DNAse ENCODE data. More conservative
$(ORG)_background_HTD.bed:
	echo "Processing genes" ; \
	for file in `find $(DB)/grsnp_db/$(ORG)/genes/ -type f -name "*.bed.gz"`; do \
		zcat $$file | grep "\bchr[0-9XYM][^_]\b" >> genes.bed; \
	done; \
	echo "Sorting and merging genes"; \
	cut -f1-3 genes.bed | sort -k1,1 -k2,2n > genes_sorted.bed && \
	mergeBed -i genes_sorted.bed > genes.bed && \
	rm genes_sorted.bed; \
	echo "Processing ENCODE"; \
	for file in `find $(DB)/grsnp_db/$(ORG)/ENCODE/ -type f -name "*.bed.gz" | grep "Histone\|Tfbs\|Dnase"`; do \
		zcat $$file | grep "\bchr[0-9XYM][^_]\b" | cut -f1-3 | >> encode.bed; \
	done; \
	echo "Sorting and merging ENCODE"; \
	cat encode.bed | sort -k1,1 -k2,2n | gzip > encode_sorted.bed.gz && \
	rm encode.bed; \
	mergeBed -i encode_sorted.bed.gz |gzip > encode.bed.gz && \
	gunzip encode.bed.gz && \
	cat genes.bed encode.bed | sort -k1,1 -k2,2n | uniq > genes_encode.bed && \
	mergeBed -i genes_encode.bed > $@; \
	rm genes_encode.bed

# Background as a masked genome, sans RepeatMasker and Blacklisted regions
hg19_background-rmsk.bed.gz:
	mysql  --user=genome --host=genome-mysql.cse.ucsc.edu -A -D hg19 -e 'select chrom,size from chromInfo' | grep "\bchr[0-9XYM][^_]\b" | sed '1d' | awk 'BEGIN {OFS="\t"} {print $$1, "0", $$2}' | sort -k1,1 -k2,2n > chromInfo_hg19.bed && \
	bedtools subtract -a chromInfo_hg19.bed -b $(DB)/grsnp_db/$(ORG)/rep/rmsk.bed.gz > tmp1.bed && \
	bedtools subtract -a tmp1.bed -b $(DB)/grsnp_db/$(ORG)/ENCODE/Special/Tier3/wgEncodeDacMapabilityConsensusExcludable.bed.gz > tmp2.bed && \
	bedtools subtract -a tmp2.bed -b $(DB)/grsnp_db/$(ORG)/ENCODE/Special/Tier3/wgEncodeDukeMapabilityRegionsExcludable.bed.gz | gzip > $@ && \
	rm chromInfo_hg19.bed tmp1.bed tmp2.bed


